### ISSUE TITLE
Pi-Hole: ignoring, 1121 non-domain entries

### ISSUE THREAD

**Issue by WoefulWrecker** [endail/cname-trackers-for-pihole#5]
Have issue with your blacklist:
  [i] Target: https://raw.githubusercontent.com/endail/cname-trackers-for-pihole/main/cname-trackers.list
  [✓] Status: Retrieval successful
  [i] Imported 97762 domains, ignoring 1121 non-domain entries
      Sample of non-domain entries:
        - .01cloud.j
        - .04510.j
        - .1000kaze.j
        - .11teamsports.b
        - .11teamsports.c

**Comment by endail** [comment]
Because PiHole is ignoring those non-domains I'm not too concerned about them. I don't manage the individual entries in the list because it's autogenerated based on [AdGuard's lists](https://github.com/AdguardTeam/cname-trackers). But they seem to have updated their repo since I created this one, and it appears there are alternate lists. I haven't done it, but you might like to try their combined list: 

https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt

I'm not sure if you would still receive the same list of non-domains though. Let me know how it goes if you do try it.
